Main svc
NovikSerg88/java-explore-with-me pull request #5
Opened 2023-10-06 10:15 UTC by NovikSerg88

2023-10-10 21:02 UTC, sergeymamonov requested changes
Проверьте везде, как вы используете String.format. Чтобы в строку вставилось передаваемое значение, нужно указать куда именно нужно вставить с помощью %s

Аннотация @Data содержит в себе несколько аннотаций. Поэтому лучше использовать именно те аннотации, которые нужны в конкретном случае.

2023-10-11 09:42 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/compilations/mapper/CompilationMapper.java
> +    public Compilation mapToEntity(NewCompilationDto dto, List<Event> events) {
Удалил неиспользуемый метод

2023-10-12 13:42 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/categories/dto/NewCategoryDto.java
> +public class NewCategoryDto {
Сделал все классы иммутабельными

2023-10-12 13:43 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/categories/dto/CategoryDto.java
> +@Data
Во всех классах заменил аннотацию @Data

2023-10-12 13:48 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +}
Добавил

2023-10-12 13:48 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/events/service/StatsServiceImpl.java
> +    private String serviceName;
Удалил неиспользуемое поле

2023-10-12 13:48 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/events/service/StatsServiceImpl.java
> +import java.util.*;
Поправил импорты

2023-10-12 14:03 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +}
Добавил обработку ServiceException

2023-10-12 14:14 UTC, NovikSerg88 commented on ewm-service/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +    public ApiError handleBadRequestException(final BadRequestException e) {
Это исключение больше не использую. Удалил за ненадобностью.

2023-10-13 05:13 UTC, sergeymamonov approved these changes

2023-10-13 05:13 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/compilations/dto/CompilationDto.java
> +@Setter
Сеттер это мутирующий метод. А dto это неизменяемый объект. Поэтому у всех dto не должно быть сеттеров.

2023-10-13 05:13 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/error/ApiError.java
> +public class ApiError {
Я бы добавил в название в конце Response. Потому что если оставить так, то как будто это ошибка, а это же не ошибка, а ответ.

2023-10-13 05:19 UTC, merged